/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/m16_a2_rifle.glb -t -r 
Author: Luchador (https://sketchfab.com/Luchador90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m16-a2-rifle-20c4bb925ca349c6b33aca176b8affba
Title: M16 A2 Rifle
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

type GLTFResult = GLTF & {
  nodes: {
    m16a2_m16a2_0: THREE.Mesh;
    magazine_m16a2_0: THREE.Mesh;
    ejection_port_cover_m16a2_0: THREE.Mesh;
    bolt_carrier_m16a2_0: THREE.Mesh;
  };
  materials: {
    m16a2: THREE.MeshStandardMaterial;
  };
};

export function M16(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./m16_a2_rifle.glb') as GLTFResult;
  const m16ref = useRef<any>(null);

  useFrame(() => {
    if (m16ref.current) m16ref.current.rotation.y += 0.01;
  });
  return (
    <group
      ref={m16ref}
      {...props}
      dispose={null}
      scale={0.1}
      position={[0, -1, -2]}
    >
      <group
        position={[-7.479, -2.902, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.54}
      >
        <mesh
          geometry={nodes.magazine_m16a2_0.geometry}
          material={materials.m16a2}
          position={[2.945, -11, 1.143]}
        />
      </group>
      <group
        position={[-9.161, 6.336, 1.741]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.54}
      >
        <mesh
          geometry={nodes.ejection_port_cover_m16a2_0.geometry}
          material={materials.m16a2}
          position={[3.607, 0.685, -2.495]}
        />
      </group>
      <group
        position={[-12.821, 7.166, 0.017]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.54}
      >
        <mesh
          geometry={nodes.bolt_carrier_m16a2_0.geometry}
          material={materials.m16a2}
          position={[5.048, 0.007, -2.821]}
        />
      </group>
      <mesh
        geometry={nodes.m16a2_m16a2_0.geometry}
        material={materials.m16a2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.54}
      />
    </group>
  );
}

useGLTF.preload('./m16_a2_rifle.glb');
